### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJOpenML.jl#17]
@JuliaRegistrator register branch=master

release notes:

- [x] (**bug fixes**) Address a number of parsing issues (#7, #8, #11) @jbrea
- [x] (**enhancement**) Add `MLJOpenML.describe_dataset`, `MLJOpenML.list_datasets`, and `MLJOpenML.list_tags` (#10) @jbrea
- [x] (**enhancement**) Introduce option `parser=...` to `MLJOpenML.load` with possible values `:csv`, `:openml` and `:auto`, and allow extra options to be passed to the CSV.jl parser (#11) @jbrea
- [x] (**enhancement**) Add alias `OpenML` for `MLJOpenML`.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**bug fixes**) Address a number of parsing issues (#7, #8, #11) @jbrea
- [x] (**enhancement**) Add `MLJOpenML.describe_dataset`, `MLJOpenML.list_datasets`, and `MLJOpenML.list_tags` (#10) @jbrea
- [x] (**enhancement**) Introduce option `parser=...` to `MLJOpenML.load` with possible values `:csv`, `:openml` and `:auto`, and allow extra options to be passed to the CSV.jl parser (#11) @jbrea
- [x] (**enhancement**) Add alias `OpenML` for `MLJOpenML`.
